import { Link } from 'react-router'
import { ArrowRight, ArrowUpRight, CalendarDays, FolderHeart, CircleCheck, TriangleAlert, Sparkles, Clock3, FileText, Activity } from 'lucide-react'
import { Page, PageTitle, Badge, Avatar, StatusBadge, AiLabel } from '@/components/shared'
import { patients, DEMO_DATE, mainCase } from '@/data/cases'
import { useApp } from '@/components/app-state'

export function Dashboard() {
  const { openSources, completed } = useApp()
  const attention = patients.filter(p => p.flags > 0).length
  return <Page><PageTitle eyebrow="Понедельник, 21 сентября" title="Обзор работы" description="Всё, что важно для взвешенного решения." action={<span className="date-label"><CalendarDays size={16} />{DEMO_DATE}</span>} />
    <div className="stats-grid">{[{ label: 'Всего дел', value: patients.length, note: 'В демонстрационном реестре', icon: FolderHeart, tone: '' }, { label: 'Требуют внимания', value: attention, note: 'Есть пробелы или расхождения', icon: TriangleAlert, tone: 'amber' }, { label: 'Готовы к рассмотрению', value: 2, note: 'Комплект проверен', icon: CircleCheck, tone: 'green' }, { label: 'Анализ завершён', value: completed.size, note: 'Сводки доступны для проверки', icon: Sparkles, tone: 'blue' }].map(({ label, value, note, icon: Icon, tone }) => <div className={`stat-card ${tone}`} key={label}><div><span>{label}</span><Icon size={19} /></div><strong>{String(value).padStart(2, '0')}</strong><small>{note}</small></div>)}</div>
    <div className="dashboard-grid"><section className="focus-case"><div className="section-top"><div className="eyebrow light">Дело в фокусе</div><Badge>Повторная МСЭ</Badge></div><div className="focus-person"><Avatar id="DEMO-001" large /><div><span className="subtle-light">DEMO-001 · Мужчина, 24 года</span><h2>Одна история.<br />Все важные детали.</h2></div></div><p className="focus-description">Сахарный диабет 1 типа с 2017 года.<br />Новые данные после предыдущего освидетельствования.</p><div className="case-milestones"><div><span>2017</span><i /><small>Диагноз</small></div><div><span>2023</span><i /><small>Первая МСЭ</small></div><div><span>2025</span><i /><small>Решение изменилось</small></div><div className="current"><span>2026</span><i /><small>Новая оценка</small></div></div><div className="focus-bottom"><div><FileText size={16} />12 документов<span>·</span><Activity size={16} />11 событий</div><Link className="button button-lime" to="/patients/DEMO-001">Открыть дело<ArrowUpRight size={17} /></Link></div></section>
    <section className="panel attention-panel"><div className="panel-heading"><div><div className="eyebrow">Приоритет сегодня</div><h2>Требует внимания <span className="count-circle">3</span></h2></div><TriangleAlert size={20} className="amber-text" /></div>{mainCase.findings.filter(f => f.group === 'missing' || f.group === 'conflict').map((f, i) => <button key={f.id} className="attention-row" onClick={() => openSources(mainCase.documents.filter(d => f.sourceIds.includes(d.id)))}><span className={`attention-symbol ${i === 2 ? 'red' : ''}`}>{i === 2 ? <Activity size={16} /> : <Clock3 size={16} />}</span><span><strong>{f.title}</strong><small>Дело DEMO-001 · проверить источник</small></span><Chevron /></button>)}<div className="attention-footer"><span className="status-dot" />Система обращает внимание. Вы решаете.</div></section></div>
    <section className="panel recent-cases"><div className="panel-heading"><div><h2>Дела в работе</h2><p>Последние обновления в вашем реестре</p></div><Link className="text-link" to="/patients">Все дела <ArrowRight size={16} /></Link></div><div className="table-scroll"><table><thead><tr><th>Пациент / дело</th><th>Основной диагноз</th><th>Статус</th><th>Обновлено</th><th><span className="sr-only">Открыть</span></th></tr></thead><tbody>{patients.slice(0, 4).map(p => <tr key={p.id}><td><Link to={`/patients/${p.id}`} className="patient-cell"><Avatar id={p.id} /><span><strong>{p.label}</strong><small>{p.id} · {p.age} лет</small></span></Link></td><td>{p.diagnosis}<small className="table-sub">{p.specialty}</small></td><td><StatusBadge status={p.status} /></td><td className="muted">{p.updated === '2026-09-21' ? 'Сегодня' : 'Вчера'}</td><td><Link to={`/patients/${p.id}`} className="icon-button" aria-label={`Открыть ${p.id}`}><ArrowUpRight size={18} /></Link></td></tr>)}</tbody></table></div></section>
    <div className="dashboard-foot"><AiLabel /><span>От разрозненных документов — к понятной истории с проверяемыми источниками.</span><Link to="/patients/DEMO-001/analysis">Попробовать анализ<ArrowRight size={16} /></Link></div>
  </Page>
}
function Chevron() { return <ArrowUpRight size={16} className="muted shrink-0" /> }
