import { useState } from 'react'
import { Link } from 'react-router'
import { FileText, Search, ArrowUpRight, Sparkles, ShieldCheck } from 'lucide-react'
import { usePatient } from '@/layouts/patient-context'
import { useApp } from '@/components/app-state'
import { Badge, EmptyState, Page, PageTitle } from '@/components/shared'
import { getCaseData, patients, formatDate } from '@/data/cases'
import type { DemoDocument } from '@/types'
type ListedDocument = DemoDocument & { patientId: string }
function DocumentList({ documents, global = false }: { documents: ListedDocument[]; global?: boolean }) {
  const { openSources } = useApp(); const [query, setQuery] = useState(''), [category, setCategory] = useState('Все категории'), [status, setStatus] = useState('Все статусы')
  const filtered = documents.filter(d => `${d.title} ${d.patientId}`.toLowerCase().includes(query.toLowerCase()) && (category === 'Все категории' || d.category === category) && (status === 'Все статусы' || d.status === status))
  return <><div className="documents-banner"><FileText size={23} /><div><strong>Документы, которым можно задать вопрос</strong><p>Откройте источник и проверьте фрагмент, на котором основан вывод.</p></div><Badge>{documents.length} документов</Badge></div><div className="panel"><div className="list-toolbar docs-toolbar"><label className="search-field"><Search size={17} /><span className="sr-only">Поиск документов</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Найти документ по названию" /></label><label><span className="sr-only">Категория документа</span><select value={category} onChange={e => setCategory(e.target.value)}><option>Все категории</option>{[...new Set(documents.map(d => d.category))].map(c => <option key={c}>{c}</option>)}</select></label><label><span className="sr-only">Статус документа</span><select value={status} onChange={e => setStatus(e.target.value)}><option>Все статусы</option><option>Проверен</option><option>Требует уточнения</option></select></label></div>{filtered.length ? <div className="documents-list">{filtered.map(d => <article key={`${d.patientId}-${d.id}`} className="document-row"><span className="file-icon"><FileText size={23} /><small>ДЕМО</small></span><div className="document-info"><button className="document-title" onClick={() => openSources([d])}>{d.title}</button><div><span>{formatDate(d.date)}</span><span>·</span><span>{d.category}</span>{global && <Link to={`/patients/${d.patientId}/documents`}>{d.patientId}</Link>}</div><Link className="document-event" to={`/patients/${d.patientId}/timeline`}>{d.event}<ArrowUpRight size={12} /></Link></div><div className="document-status"><Badge tone={d.status === 'Проверен' ? 'green' : 'amber'}>{d.status}</Badge>{d.usedByAI && <span><Sparkles size={12} />Источник для AI</span>}</div><button className="icon-button" aria-label={`Открыть документ: ${d.title}`} onClick={() => openSources([d])}><ArrowUpRight size={18} /></button></article>)}</div> : <EmptyState action={<button className="text-link" onClick={() => { setQuery(''); setCategory('Все категории'); setStatus('Все статусы') }}>Сбросить фильтры</button>} />}<div className="list-footer"><span>Найдено: {filtered.length}</span><span><ShieldCheck size={13} />Локальный демонстрационный комплект</span></div></div></>
}
export function Documents() { const { patient, data } = usePatient(); return <DocumentList documents={data.documents.map(d => ({ ...d, patientId: patient.id }))} /> }
export function AllDocuments() { return <Page><PageTitle eyebrow="Библиотека источников" title="Документы" description="Все демонстрационные комплекты, связанные с делами пациентов." /><DocumentList global documents={patients.flatMap(p => getCaseData(p).documents.map(d => ({ ...d, patientId: p.id })))} /></Page> }
