import { Link } from 'react-router'
import { ArrowRight, Activity, ClipboardCheck, FileText, Hospital, Sparkles, TriangleAlert } from 'lucide-react'
import { usePatient } from '@/layouts/patient-context'
import { useApp } from '@/components/app-state'
import { AiLabel, Badge, HumanNote, SourceButton } from '@/components/shared'
import { formatDate } from '@/data/cases'

export function PatientOverview() {
  const { patient, data } = usePatient(), { openSources } = useApp(); const isMain = patient.id === 'DEMO-001', base = `/patients/${patient.id}`
  const flags = data.findings.filter(f => f.group === 'missing' || f.group === 'conflict')
  return <div className="patient-overview"><div className="overview-main"><section className="panel case-summary"><div className="panel-heading"><h2>Кратко о деле</h2><Badge tone="green">{isMain ? 'Повторная оценка' : 'Демо-сводка'}</Badge></div><div className="panel-body"><p className="summary-lead">{isMain ? '9 лет истории заболевания. Решение МСЭ изменилось. После последней оценки появились новые медицинские данные.' : `Демонстрационный случай: ${patient.diagnosis.toLowerCase()}. Доступна сокращённая сводка для знакомства с интерфейсом.`}</p><div className="overview-facts"><div><span>Основной диагноз</span><strong>{patient.diagnosis}</strong></div><div><span>Профиль дела</span><strong>{patient.specialty}</strong></div><div><span>Начало наблюдения</span><strong>{isMain ? 'Июнь 2017' : 'Не указано в сводке'}</strong></div><div><span>Последняя МСЭ</span><strong>{isMain ? '20 июня 2025' : 'Нет сведений'}</strong></div></div><SourceButton onClick={() => openSources(data.documents.filter(d => isMain ? ['d1', 'd4', 'd6'].includes(d.id) : true))} /></div></section>
    <div className="overview-metrics"><div><Hospital size={18} /><strong>{isMain ? '2' : '—'}</strong><span>Госпитализации за год</span></div><div><FileText size={18} /><strong>{data.documents.length}</strong><span>Документов в деле</span></div><div><ClipboardCheck size={18} /><strong>{isMain ? '3' : '—'}</strong><span>Решения МСЭ в истории</span></div></div>
    {isMain && <section className="panel lab-panel"><div className="panel-heading"><div><h2>Динамика HbA1c</h2><p>Из документов дела · демонстрационные значения</p></div><Badge tone="amber">Требует оценки врача</Badge></div><div className="lab-chart"><div className="chart-value">9,1<span>%</span><small>Март 2026</small></div><div className="chart-plot"><svg viewBox="0 0 420 110" role="img" aria-label="HbA1c: 8,2% в 2024, 7,8% в 2025, 9,1% в марте 2026"><path d="M10 90H410M10 55H410M10 20H410" stroke="#e7ede1" strokeDasharray="4 5" fill="none" /><path d="M20 55L200 80L400 18L400 100H20Z" fill="#edf3e5" /><path d="M20 55L200 80L400 18" fill="none" stroke="#92a975" strokeWidth="2" />{[[20, 55], [200, 80], [400, 18]].map(([x, y]) => <circle key={x} cx={x} cy={y} r="4" fill="#fff" stroke="#739453" strokeWidth="2" />)}</svg><div className="chart-labels"><span>2024 · 8,2%</span><span>2025 · 7,8%</span><span>2026 · 9,1%</span></div></div></div><div className="panel-bottom"><SourceButton count={2} onClick={() => openSources(data.documents.filter(d => ['d8', 'd12'].includes(d.id)))} /><span>Показатель сам по себе не определяет решение МСЭ</span></div></section>}
    <section className="panel"><div className="panel-heading"><h2>Последние события</h2><Link className="text-link" to={`${base}/timeline`}>Вся история<ArrowRight size={15} /></Link></div><div className="compact-events">{data.events.slice(-3).reverse().map(e => <div key={e.id}><span className="small-event-icon"><Activity size={16} /></span><div><small>{formatDate(e.date)} · {e.type}</small><h3>{e.title}</h3><SourceButton onClick={() => openSources(data.documents.filter(d => d.id === e.sourceId))} /></div></div>)}</div></section>
  </div><aside className="overview-aside"><section className="panel overview-attention"><div className="panel-heading"><h2><TriangleAlert size={18} />Требует внимания</h2><Badge tone="amber">{flags.length}</Badge></div>{flags.length ? flags.map(f => <div className="flag-item" key={f.id}><h3>{f.title}</h3><p>{f.description}</p><SourceButton count={f.sourceIds.length} onClick={() => openSources(data.documents.filter(d => f.sourceIds.includes(d.id)))} /></div>) : <div className="panel-body"><p className="muted">В сокращённой демо-сводке нет отмеченных расхождений. Это не означает полноту медицинской истории.</p></div>}</section><section className="analysis-callout"><AiLabel /><h2>Собрать всё важное<br />в одну картину</h2><p>Подтверждения, пробелы и новые сведения с прямыми ссылками на документы.</p><Link className="button button-primary" to={`${base}/analysis`}><Sparkles size={16} />Перейти к AI-анализу</Link></section><HumanNote /></aside></div>
}
