import { Download, Printer, FileCheck2, ShieldCheck, ArrowUpRight } from 'lucide-react'
import { usePatient } from '@/layouts/patient-context'
import { useApp } from '@/components/app-state'
import { Badge, HumanNote, SourceButton } from '@/components/shared'
import { Button } from '@/components/ui/button'
import { formatDate, DEMO_DATE } from '@/data/cases'

export function Report() {
  const { patient, data } = usePatient(), { openSources, notify } = useApp()
  const sections = [
    { title: 'История заболевания', text: data.events.slice(0, 4).map(e => `${formatDate(e.date)} — ${e.title}. ${e.description}`).join(' '), sources: [...new Set(data.events.slice(0, 4).map(e => e.sourceId))] },
    { title: 'Последние изменения и госпитализации', text: data.findings.filter(f => f.group === 'changed' || f.id === 'f2').map(f => `${f.title}. ${f.description}`).join(' ') || 'В сокращённом комплекте нет сведений о динамике и госпитализациях.', sources: data.findings.filter(f => f.group === 'changed' || f.id === 'f2').flatMap(f => f.sourceIds) },
    { title: 'Лечение', text: patient.id === 'DEMO-001' ? 'Инсулинотерапия отражена в документах 2024–2025 годов. В октябре 2025 выполнена коррекция терапии в стационаре. Дозировки и назначения в прототипе не приводятся.' : 'В сокращённой демонстрационной сводке лечение не описано.', sources: patient.id === 'DEMO-001' ? ['d11', 'd5'] : [] },
    { title: 'Осложнения и противоречия', text: data.findings.filter(f => f.group === 'conflict').map(f => `${f.title}. ${f.description}`).join(' ') || 'Нет доступных сведений для проверки осложнений и противоречий.', sources: data.findings.filter(f => f.group === 'conflict').flatMap(f => f.sourceIds) },
    { title: 'Отсутствующие сведения', text: data.findings.filter(f => f.group === 'missing').map(f => `${f.title}. ${f.description}`).join(' ') || 'Полнота истории не оценивалась: представлен сокращённый демонстрационный комплект.', sources: data.findings.filter(f => f.group === 'missing').flatMap(f => f.sourceIds) },
  ]
  function download() {
    const content = `DEREK · ДЕМОНСТРАЦИОННОЕ ДОСЬЕ\n${patient.id} · ${DEMO_DATE}\nВсе сведения вымышлены. Не является медицинским заключением.\n\n${patient.label}, ${patient.sex.toLowerCase()}, ${patient.age} лет\n${patient.diagnosis} (${patient.code})\n\n${sections.map((s, i) => `${i + 1}. ${s.title}\n${s.text}\nИсточники: ${[...new Set(s.sources)].map(id => { const d = data.documents.find(doc => doc.id === id); return d ? `${d.title} (${formatDate(d.date)})` : '' }).join('; ') || 'нет в комплекте'}`).join('\n\n')}\n\nКлючевые документы\n${data.documents.map(d => `${d.title} · ${formatDate(d.date)}\n${d.excerpt}`).join('\n\n')}\n\nРешение принимает комиссия. AI не определяет право на инвалидность.`
    const url = URL.createObjectURL(new Blob(['\uFEFF', content], { type: 'text/plain;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `Derek-${patient.id}-досье.txt`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notify('Досье скачано в TXT. Для PDF используйте «Печать → Сохранить как PDF».')
  }
  return <div><div className="section-heading report-controls"><div><h2>Досье для комиссии</h2><p>Готовая сводка для проверки и обсуждения</p></div><div className="heading-actions"><Button variant="outline" onClick={() => window.print()}><Printer size={16} />Печать</Button><Button onClick={download}><Download size={16} />Скачать отчёт</Button></div></div><div className="report-layout"><article className="report-sheet"><div className="report-letterhead"><div><span className="report-brand">derek.</span><span>Помощник медицинской комиссии</span></div><Badge>ДЕМОНСТРАЦИОННОЕ ДОСЬЕ</Badge></div><div className="report-title"><span className="eyebrow">Материалы к рассмотрению · {patient.id}</span><h2>Медицинская история.<br />Краткая сводка.</h2><p>Подготовлено: {DEMO_DATE}</p></div><div className="report-patient"><div><span>Пациент</span><strong>{patient.label} · {patient.sex.toLowerCase()}, {patient.age} лет</strong></div><div><span>Основной диагноз</span><strong>{patient.diagnosis} · {patient.code}</strong></div></div>{sections.map((s, i) => <section className="report-section" key={s.title}><div><span>{String(i + 1).padStart(2, '0')}</span><h3>{s.title}</h3></div><p>{s.text}</p>{s.sources.length > 0 && <SourceButton count={new Set(s.sources).size} onClick={() => openSources(data.documents.filter(d => s.sources.includes(d.id)))} />}</section>)}<section className="report-section"><div><span>06</span><h3>Ключевые подтверждающие документы</h3></div><ol className="report-sources">{data.documents.filter(d => d.usedByAI).map(d => <li key={d.id}><button onClick={() => openSources([d])}>{d.title}<ArrowUpRight size={12} /></button><span>{formatDate(d.date)}</span></li>)}</ol></section><div className="report-disclaimer"><ShieldCheck size={18} /><p>Все сведения вымышлены. Это демонстрационная сводка, а не медицинское заключение. Окончательное решение принимает комиссия после проверки полного комплекта документов.</p></div><div className="report-signature"><span>Derek · {patient.id}</span><span>Подготовлено для демонстрации</span></div></article><aside className="report-aside"><FileCheck2 size={27} /><h3>Перед рассмотрением</h3><p>Сверьте сводку с оригиналами и дополните недостающие сведения.</p><ul><li>Проверить источники</li><li>Уточнить расхождения</li><li>Запросить недостающие данные</li><li>Обсудить на комиссии</li></ul><span>Скачивание: текстовый файл.<br />Печать: отдельный чистый макет.</span><HumanNote /></aside></div></div>
}
