import { useState } from 'react'
import { motion } from 'motion/react'
import { Activity, ArrowDownWideNarrow, CalendarDays, FileText, HeartPulse, Hospital, Pill, Stethoscope, Scissors } from 'lucide-react'
import { usePatient } from '@/layouts/patient-context'
import { useApp } from '@/components/app-state'
import { Badge, EmptyState, SourceButton } from '@/components/shared'
import { formatDate } from '@/data/cases'
import type { EventType } from '@/types'
const icons = { Диагноз: Stethoscope, Госпитализация: Hospital, Анализы: Activity, МСЭ: FileText, Лечение: Pill, Осложнение: HeartPulse, Операция: Scissors }
const types: EventType[] = ['Диагноз', 'Госпитализация', 'Анализы', 'МСЭ', 'Лечение', 'Осложнение', 'Операция']
export function Timeline() {
  const { data } = usePatient(), { openSources } = useApp(); const [type, setType] = useState('Все события'), [reverse, setReverse] = useState(true)
  const events = data.events.filter(e => type === 'Все события' || e.type === type).sort((a, b) => reverse ? b.date.localeCompare(a.date) : a.date.localeCompare(b.date))
  return <div><div className="section-heading"><div><h2>Медицинская история</h2><p>События, которые складываются в полную картину</p></div><button className="text-link" onClick={() => setReverse(!reverse)}><ArrowDownWideNarrow size={16} />{reverse ? 'Сначала новые' : 'Сначала ранние'}</button></div><div className="timeline-filters" role="group" aria-label="Тип события">{['Все события', ...types].map(t => <button key={t} onClick={() => setType(t)} aria-pressed={type === t} className={type === t ? 'selected' : ''}>{t}</button>)}</div><div className="timeline-layout"><section className="medical-timeline" aria-label="События истории">{events.length ? events.map((e, i) => { const Icon = icons[e.type]; const year = e.date.slice(0, 4); return <motion.article initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .2, delay: Math.min(i * .025, .15) }} key={e.id} className="timeline-event"><div className="timeline-year">{i === 0 || events[i - 1].date.slice(0, 4) !== year ? year : ''}</div><div className={`timeline-node ${e.type === 'МСЭ' ? 'node-mse' : ''}`}><Icon size={17} /></div><div className="timeline-content"><div><Badge tone={e.type === 'МСЭ' ? 'green' : e.type === 'Осложнение' ? 'amber' : 'neutral'}>{e.type}</Badge><time dateTime={e.date}>{formatDate(e.date)}</time></div><h3>{e.title}</h3><p>{e.description}</p><SourceButton onClick={() => openSources(data.documents.filter(d => d.id === e.sourceId))} /></div></motion.article> }) : <EmptyState title="Событий этого типа нет" description="В текущем демонстрационном комплекте такие события не представлены." />}</section><aside className="timeline-guide"><CalendarDays size={23} /><h3>История без пробелов?</h3><p>Шкала отражает только доступные документы. Отсутствие события в истории не означает, что оно не происходило.</p><div><strong>{events.length}</strong><span>событий показано</span></div><div><strong>{data.documents.length}</strong><span>документов в комплекте</span></div><span className="guide-note">Нажмите «Посмотреть источник», чтобы проверить запись.</span></aside></div></div>
}
