import { useState, useEffect, useRef } from 'react'
import { Link, NavLink, Outlet, useLocation } from 'react-router'
import { LayoutDashboard, FolderHeart, Files, ArrowUpRight, Menu, Bell, HelpCircle, ChevronRight, ShieldCheck, Search, Sparkles } from 'lucide-react'
import { Brand, Badge } from '@/components/shared'
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'

const links = [{ to: '/dashboard', label: 'Обзор работы', icon: LayoutDashboard }, { to: '/patients', label: 'Дела пациентов', icon: FolderHeart }, { to: '/documents', label: 'Документы', icon: Files }]
function Sidebar({ onNavigate, onHelp }: { onNavigate?: () => void; onHelp: () => void }) { return <div className="sidebar-inner"><Brand light /><div className="workspace-label">Рабочее пространство</div><nav aria-label="Основная навигация">{links.map(({ to, label, icon: Icon }) => <NavLink to={to} key={to} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`} onClick={onNavigate}><Icon size={19} /><span>{label}</span>{to === '/patients' && <span className="nav-count">6</span>}</NavLink>)}</nav><div className="sidebar-divider" /><div className="workspace-label">Быстрый доступ</div><Link to="/patients/DEMO-001" className="nav-item" onClick={onNavigate}><span className="case-dot" />Демонстрационное дело<ArrowUpRight size={15} /></Link><div className="sidebar-bottom"><div className="sidebar-note"><ShieldCheck size={23} /><h3>Данные под контролем</h3><p>Только вымышленные дела.<br />Без внешних интеграций.</p><span>Демонстрационная среда</span></div><button className="nav-item help-button" onClick={onHelp}><HelpCircle size={18} />Как работает Derek</button><div className="user-profile"><div className="user-initials">ЭК</div><div><strong>Эксперт комиссии</strong><span>Демонстрационный доступ</span></div></div></div></div> }
export function AppLayout() {
  const [menu, setMenu] = useState(false), [help, setHelp] = useState(false), [notifications, setNotifications] = useState(false)
  const location = useLocation(); const mainRef = useRef<HTMLElement>(null)
  useEffect(() => { window.scrollTo(0, 0); mainRef.current?.focus({ preventScroll: true }); document.title = 'Derek — рабочее пространство комиссии' }, [location.pathname])
  const section = location.pathname.startsWith('/patients') ? 'Дела пациентов' : location.pathname.startsWith('/documents') ? 'Документы' : 'Обзор работы'
  return <div className="app-shell"><a href="#main" className="skip-link">Перейти к содержимому</a><aside className="desktop-sidebar"><Sidebar onHelp={() => setHelp(true)} /></aside><div className="workspace"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" aria-label="Открыть меню" onClick={() => setMenu(true)}><Menu size={22} /></button><span className="topbar-context">Рабочее пространство</span><ChevronRight size={14} /><span>{section}</span></div><div className="topbar-right"><Badge tone="green"><span className="status-dot" />Демо-режим</Badge><Link to="/patients" className="icon-button" aria-label="Найти дело"><Search size={19} /></Link><button className="icon-button notification-button" aria-label="Открыть уведомления" onClick={() => setNotifications(true)}><Bell size={19} /><i /></button><div className="header-avatar" aria-label="Демонстрационный профиль эксперта">ЭК</div></div></header><main id="main" ref={mainRef} tabIndex={-1}><Outlet /></main><footer className="app-footer"><span>Derek · Помощник медицинской комиссии</span><span>Все данные вымышлены · Демо 2026</span></footer></div>
    <Sheet open={menu} onOpenChange={setMenu}><SheetContent side="left" className="mobile-sidebar"><SheetTitle className="sr-only">Навигация</SheetTitle><SheetDescription className="sr-only">Разделы рабочего пространства Derek</SheetDescription><Sidebar onNavigate={() => setMenu(false)} onHelp={() => { setMenu(false); setHelp(true) }} /></SheetContent></Sheet>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>От документов — к ясной картине</DialogTitle><DialogDescription>Derek готовит материалы к рассмотрению, а не определяет право на инвалидность.</DialogDescription></DialogHeader><ol className="help-steps"><li><span>01</span><div><strong>Откройте дело</strong><p>Изучите историю и документы пациента.</p></div></li><li><span>02</span><div><strong>Запустите демонстрационный анализ</strong><p>Получите сводку изменений, пробелов и противоречий.</p></div></li><li><span>03</span><div><strong>Проверьте источники</strong><p>Каждый вывод связан с фрагментом документа.</p></div></li><li><span>04</span><div><strong>Подготовьте досье</strong><p>Скачайте или распечатайте материалы для комиссии.</p></div></li></ol><Button onClick={() => setHelp(false)}>Всё понятно</Button></DialogContent></Dialog>
    <Dialog open={notifications} onOpenChange={setNotifications}><DialogContent><DialogHeader><DialogTitle>Требует вашего внимания</DialogTitle><DialogDescription>События демонстрационного рабочего пространства</DialogDescription></DialogHeader><div className="notification-item"><Sparkles size={22} /><div><h3>В деле DEMO-001 есть новые данные</h3><p>Две госпитализации после предыдущей МСЭ. Проверьте источники и полноту комплекта.</p><Link to="/patients/DEMO-001/analysis" className="text-link" onClick={() => setNotifications(false)}>Открыть анализ <ArrowUpRight size={14} /></Link></div></div></DialogContent></Dialog>
  </div>
}
